apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-ext
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ledoantruc/demo-repo.git
    targetRevision: main
    path: kong-staging
    plugin:
      name: helmOciGarPlugin
      env:
        - name: NAME
          value: $ARGOCD_APP_NAME
        - name: VALUES
          value: values.yaml
        - name: NAMESPACE
          value: $ARGOCD_APP_NAMESPACE
          
  destination:
    server: https://kubernetes.default.svc
    namespace: kong-ext

  syncPolicy:
    automated:
      selfHeal: true
      prune: true